from app import app

import os

from flask import render_template, send_from_directory

from dotenv import load_dotenv
from pymongo import MongoClient
from bson.json_util import dumps

load_dotenv()

DB_NAME = os.getenv('DB_NAME')
DB_USERNAME = os.getenv('DB_USERNAME')
DB_PASSWORD = os.getenv('DB_PASSWORD')

client = MongoClient(
    f"mongodb+srv://{DB_USERNAME}:{DB_PASSWORD}@covid19-kfupm.8orak.azure.mongodb.net/{DB_NAME}?retryWrites=true&w=majority"
)
db = client[DB_NAME]
regions_collection = db['regions']
cities_collection = db['cities']
misc_collection = db['misc_info']


@app.route("/<path:path>", methods=["GET"])
def static_proxy(path):
    """Returns static files"""
    return send_from_directory("static", path)


@app.route("/")
def index():
    """Returns index.html (generated by Angular)"""
    return render_template("index.html")


@app.route('/total')
def get_total():
    return dumps(regions_collection.find({
        '_id': 'All Regions'
    }))


@app.route('/all-regions')
def get_regions():
    return dumps(regions_collection.find({
        '_id': {'$ne': 'All Regions'}
    }))


@app.route('/all-cities')
def get_cities():
    return dumps(cities_collection.find())


@app.errorhandler(503)
def internal_error(error):
    return "Something went wrong. Contact the administrator."
